name: Weekly Defang Compose Up

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  defang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Defang CLI
      run: |
        curl -L https://github.com/DefangLabs/defang/releases/latest/download/defang-linux-amd64 -o defang
        chmod +x defang

    - name: Run Defang Compose Up
      run: ./defang compose up
